### ISSUE TITLE
Accessing latest 21Q3 data from Depmap package 

### ISSUE THREAD

**Issue by nobes1** [UCLouvain-CBIO/depmap#71] opened 2021-09-15 12:44 UTC
I've installed Depmap version 1.7.1 but I can only view data releases upto 21Q1. 

`BiocManager::install(version='devel')`
`BiocManager::install("depmap")`

Is there a step I'm missing to access the latest datasets? 

`library("depmap")`
`library("ExperimentHub")`
`query(eh, "depmap")`
`depmap_crispr()`

Thank you for your work on this package it's fantastically useful.

**Comment by lgatto** [comment] 2021-09-15 14:11
Indeed, thank you for highlighting this. @tfkillian - could you check with the Lori, or the person that you informed about the latest push, please.

**Comment by tfkillian** [comment] 2021-09-16 10:48
@lgatto The cleaned 21Q3 Depmap data was pushed to EH before depmap 1.7.1 was pushed, so the problem is not with Lori or EH. The following code works for me and I am able to access the 21Q3 data on my machine.

@nobes1 I would suggest accessing the latest datasets using the EH accession number as an interim solution until we figure out exactly what the error is with the depmap_*() functions. e.g. to access the 21Q3 CRISPR dependency dataset:
 crispr <- eh[["EH6753"]] 

## code
library("depmap")
library("ExperimentHub")
eh <- ExperimentHub()
> snapshotDate(): 2021-09-13
query(eh, "depmap")

  EH6753 | crispr_21Q3       
  EH6754 | copyNumber_21Q3   
  EH6755 | TPM_21Q3          
  EH6756 | mutationCalls_21Q3
  EH6757 | metadata_21Q3

depmap_crispr()
snapshotDate(): 2021-09-13
see ?depmap and browseVignettes('depmap') for documentation
downloading 1 resources
retrieving 1 resource
  |=============================================================| 100%

loading from cache
# A tibble: 17,949,576 × 6
   depmap_id  gene     dependency entrez_id gene_name cell_line        
   <chr>      <chr>         <dbl>     <int> <chr>     <chr>            
 1 ACH-000001 A1BG (1)    -0.148          1 A1BG      NIHOVCAR3_OVARY  
 2 ACH-000004 A1BG (1)     0.0423         1 A1BG      HEL_HAEMATOPOIET…
 3 ACH-000005 A1BG (1)    -0.0973         1 A1BG      HEL9217_HAEMATOP…
 4 ACH-000007 A1BG (1)    -0.0211         1 A1BG      LS513_LARGE_INTE…
 5 ACH-000009 A1BG (1)    -0.0222         1 A1BG      C2BBE1_LARGE_INT…
 6 ACH-000011 A1BG (1)     0.0794         1 A1BG      253J_URINARY_TRA…
 7 ACH-000012 A1BG (1)    -0.142          1 A1BG      HCC827_LUNG      
 8 ACH-000013 A1BG (1)    -0.0583         1 A1BG      ONCODG1_OVARY    
 9 ACH-000014 A1BG (1)    -0.0233         1 A1BG      HS294T_SKIN      
10 ACH-000015 A1BG (1)    -0.171          1 A1BG      NCIH1581_LUNG    
# … with 17,949,566 more rows

sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] depmap_1.7.1        dplyr_1.0.7         ExperimentHub_2.1.4
[4] AnnotationHub_3.1.5 BiocFileCache_2.1.1 dbplyr_2.1.1       
[7] BiocGenerics_0.39.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7                    lubridate_1.7.10             
 [3] Biostrings_2.61.2             png_0.1-7                    
 [5] assertthat_0.2.1              digest_0.6.27                
 [7] utf8_1.2.2                    mime_0.11                    
 [9] GenomeInfoDb_1.29.8           R6_2.5.1                     
[11] stats4_4.1.1                  RSQLite_2.2.8                
[13] evaluate_0.14                 httr_1.4.2                   
[15] pillar_1.6.2                  zlibbioc_1.39.0              
[17] rlang_0.4.11                  curl_4.3.2                   
[19] rstudioapi_0.13               blob_1.2.2                   
[21] S4Vectors_0.31.3              rmarkdown_2.11               
[23] readr_2.0.1                   stringr_1.4.0                
[25] RCurl_1.98-1.4                bit_4.0.4                    
[27] shiny_1.6.0                   compiler_4.1.1               
[29] httpuv_1.6.3                  janitor_2.1.0                
[31] xfun_0.26                     pkgconfig_2.0.3              
[33] htmltools_0.5.2               tidyselect_1.1.1             
[35] KEGGREST_1.33.0               GenomeInfoDbData_1.2.6       
[37] tibble_3.1.4                  interactiveDisplayBase_1.31.2
[39] IRanges_2.27.2                fansi_0.5.0                  
[41] withr_2.4.2                   crayon_1.4.1                 
[43] tzdb_0.1.2                    later_1.3.0                  
[45] bitops_1.0-7                  rappdirs_0.3.3               
[47] xtable_1.8-4                  lifecycle_1.0.0              
[49] DBI_1.1.1                     magrittr_2.0.1               
[51] stringi_1.7.4                 cachem_1.0.6                 
[53] XVector_0.33.0                promises_1.2.0.1             
[55] snakecase_0.11.0              ellipsis_0.3.2               
[57] filelock_1.0.2                generics_0.1.0               
[59] vctrs_0.3.8                   BiocStyle_2.21.3             
[61] tools_4.1.1                   bit64_4.0.5                  
[63] Biobase_2.53.0                glue_1.4.2                   
[65] purrr_0.3.4                   BiocVersion_3.14.0           
[67] hms_1.1.0                     fastmap_1.1.0                
[69] yaml_2.2.1                    AnnotationDbi_1.55.1         
[71] BiocManager_1.30.16           memoise_2.0.0                
[73] knitr_1.34

**Comment by nobes1** [comment] 2021-09-16 15:51
After updating some of the dependencies I can now access a more recent snapshot of the data but still not 21Q3 frustratingly. On loadining the depmap package the output says 'This is depmap release 21Q3 but the eh objects only go upto 21Q2. Am I missing something? 

```{r}
> library("depmap")
snapshotDate(): 2021-05-18
This is depmap release 21Q3
> library("ExperimentHub")
> eh <- ExperimentHub()
snapshotDate(): 2021-05-18
> query(eh, "depmap")
ExperimentHub with 58 records
# snapshotDate(): 2021-05-18
# $dataprovider: Broad Institute
# $species: Homo sapiens
# $rdataclass: tibble
# additional mcols(): taxonomyid, genome, description, coordinate_1_based, maintainer, rdatadateadded, preparerclass,
#   tags, rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH2260"]]' 

           title             
  EH2260 | rnai_19Q1         
  EH2261 | crispr_19Q1       
  EH2262 | copyNumber_19Q1   
  EH2263 | RPPA_19Q1         
  EH2264 | TPM_19Q1          
  ...      ...               
  EH6118 | crispr_21Q2       
  EH6119 | copyNumber_21Q2   
  EH6120 | TPM_21Q2          
  EH6121 | mutationCalls_21Q2
  EH6122 | metadata_21Q2  
     
> depmap_crispr()
snapshotDate(): 2021-05-18
see ?depmap and browseVignettes('depmap') for documentation
loading from cache
# A tibble: 17,468,550 x 6
   depmap_id  gene     dependency entrez_id gene_name cell_line                                 
   <chr>      <chr>         <dbl>     <int> <chr>     <chr>                                     
 1 ACH-000001 A1BG (1)   -0.335           1 A1BG      NIHOVCAR3_OVARY                           
 2 ACH-000004 A1BG (1)    0.0201          1 A1BG      HEL_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE    
 3 ACH-000005 A1BG (1)   -0.191           1 A1BG      HEL9217_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE
 4 ACH-000007 A1BG (1)    0.00886         1 A1BG      LS513_LARGE_INTESTINE                     
 5 ACH-000009 A1BG (1)    0.00648         1 A1BG      C2BBE1_LARGE_INTESTINE                    
 6 ACH-000011 A1BG (1)    0.145           1 A1BG      253J_URINARY_TRACT                        
 7 ACH-000012 A1BG (1)   -0.135           1 A1BG      HCC827_LUNG                               
 8 ACH-000013 A1BG (1)   -0.0931          1 A1BG      ONCODG1_OVARY                             
 9 ACH-000014 A1BG (1)    0.00957         1 A1BG      HS294T_SKIN                               
10 ACH-000015 A1BG (1)   -0.233           1 A1BG      NCIH1581_LUNG                             
# ... with 17,468,540 more rows
> crispr <- eh[["EH6753"]] 
Error: EH6753 added after current Hub snapshot date.
  added: 2021-08-26
  snapshote date: 2021-05-18
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] depmap_1.7.1        dplyr_1.0.7         ExperimentHub_2.0.0 AnnotationHub_3.0.1 BiocFileCache_2.0.0 dbplyr_2.1.1       
[7] BiocGenerics_0.38.0
```

**Comment by tfkillian** [comment] 2021-09-16 16:00
@nobes1 It appears that you are running `ExperimentHub_2.0.0` whereas I am running `ExperimentHub_2.1.4`. Is it possible for you to update `ExperimentHub` to a newer version? This may be the source of your problem.

**Comment by nobes1** [comment] 2021-09-16 16:10
Thanks. Apologies for the simple question but what’s the best way to do this? I tried detaching and then removing the package and installing again but it has reinstalled version 2.0.0.
________________________________

**Comment by tfkillian** [comment] 2021-09-16 16:23
@nobes1 Perhaps you can try the following:

`require(devtools)`
`devtools::install_github("Bioconductor/ExperimentHub", force = TRUE)`

**Comment by lgatto** [comment] 2021-09-16 16:32
@nobes1 - you need to use a more recent version of Bioconductor. Current release is 3.13, and the devel version is 3.14. You can do this with 

```r
BiocManager::install(version = "3.14")
```
This will update your complete Bioconductor installation to the latest version using R 4.1.1. There is a risk in cherry picking single packages and mixing release/devel versions. 

For more details on using the devel version, see http://bioconductor.org/developers/how-to/useDevel/. 

I'm closing the issue for now, but feel free to re-open it if needed.

**Closed by lgatto** 2021-09-16 16:32 UTC
