### ISSUE TITLE
installation errors.

### ISSUE THREAD

**Issue by Travis13197** [UCLouvain-CBIO/depmap#85] opened 2023-04-12 14:56 UTC
install_github("UCLouvain-CBIO/depmap")

info:
Warning: package 'dplyr' was built under R version 4.2.3
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
snapshotDate(): 2023-04-11
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: FUN(X[[i]], ...)
  error: 'crispr_22Q1' not found in ExperimentHub
Error: loading failed
Execution halted
ERROR: loading failed

i don't know how to fix this. please help

**Comment by Travis13197** [comment] 2023-04-12 14:57
install_github("UCLouvain-CBIO/depmap")
BiocManager::install("depmap",version = "3.16")
remotes::install_github("UCLouvain-CBIO/depmap", ref ="4a9f52ed6cf9c3821891ebdd9db317194d6518c9")

those methods can't help either.

**Comment by lgatto** [comment] 2023-04-12 16:54
Could you please provide the complete inputs and outputs and your session information (with `sessionInfo()`).

Also, do not install from Github, this is likely to fail, only use `BiocManager::install("depmap")` (without setting the version). If you need a more recent version of depmap, you will need to have a recent version of R.

**Comment by Travis13197** [comment] 2023-04-13 04:44
**Thanks! Here is session info:**
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] enrichplot_1.18.4     DOSE_3.24.2           org.Mm.eg.db_3.16.0   AnnotationDbi_1.60.2  Biobase_2.58.0        clusterProfiler_4.6.2
 [7] ggfortify_0.4.16      data.table_1.14.8     ggpubr_0.6.0          rtracklayer_1.58.0    GenomicRanges_1.50.2  GenomeInfoDb_1.34.9  
[13] IRanges_2.32.0        S4Vectors_0.36.2      BiocGenerics_0.44.0   stringr_1.5.0         dplyr_1.1.1           tidyr_1.3.0          
[19] msigdbr_7.5.1         ggplot2_3.4.2        

loaded via a namespace (and not attached):
  [1] ggtree_3.6.2                fgsea_1.24.0                colorspace_2.1-0            gson_0.1.0                  ggsignif_0.6.4             
  [6] rjson_0.2.21                qvalue_2.30.0               XVector_0.38.0              aplot_0.1.10                rstudioapi_0.14            
 [11] farver_2.1.1                remotes_2.4.2               graphlayouts_0.8.4          ggrepel_0.9.3               bit64_4.0.5                
 [16] scatterpie_0.1.8            fansi_1.0.4                 codetools_0.2-19            splines_4.2.2               cachem_1.0.7               
 [21] GOSemSim_2.24.0             polyclip_1.10-4             jsonlite_1.8.4              Rsamtools_2.14.0            broom_1.0.4                
 [26] GO.db_3.16.0                png_0.1-8                   ggforce_0.4.1               BiocManager_1.30.20         compiler_4.2.2             
 [31] httr_1.4.5                  backports_1.4.1             lazyeval_0.2.2              Matrix_1.5-4                fastmap_1.1.1              
 [36] cli_3.6.1                   tweenr_2.0.2                tools_4.2.2                 igraph_1.4.2                gtable_0.3.3               
 [41] glue_1.6.2                  GenomeInfoDbData_1.2.9      reshape2_1.4.4              fastmatch_1.1-3             Rcpp_1.0.10                
 [46] carData_3.0-5               vctrs_0.6.1                 Biostrings_2.66.0           nlme_3.1-162                ape_5.7-1                  
 [51] babelgene_22.9              ggraph_2.1.0                MeSHDbi_1.34.0              lifecycle_1.0.3             restfulr_0.0.15            
 [56] rstatix_0.7.2               XML_3.99-0.14               zlibbioc_1.44.0             MASS_7.3-58.3               scales_1.2.1               
 [61] tidygraph_1.2.3             vroom_1.6.1                 MatrixGenerics_1.10.0       parallel_4.2.2              SummarizedExperiment_1.28.0
 [66] RColorBrewer_1.1-3          yaml_2.3.7                  memoise_2.0.1               gridExtra_2.3               downloader_0.4             
 [71] ggfun_0.0.9                 HDO.db_0.99.1               yulab.utils_0.0.6           stringi_1.7.12              RSQLite_2.3.0              
 [76] BiocIO_1.8.0                tidytree_0.4.2              BiocParallel_1.32.6         rlang_1.1.0                 pkgconfig_2.0.3            
 [81] matrixStats_0.63.0          bitops_1.0-7                lattice_0.21-8              purrr_1.0.1                 treeio_1.22.0              
 [86] patchwork_1.1.2             GenomicAlignments_1.34.1    shadowtext_0.1.2            cowplot_1.1.1               bit_4.0.5                  
 [91] tidyselect_1.2.0            plyr_1.8.8                  magrittr_2.0.3              R6_2.5.1                    generics_0.1.3             
 [96] DelayedArray_0.23.2         DBI_1.1.3                   pillar_1.9.0                withr_2.5.0                 KEGGREST_1.38.0            
[101] abind_1.4-5                 RCurl_1.98-1.12             tibble_3.2.1                crayon_1.5.2                car_3.1-2                  
[106] utf8_1.2.3                  tzdb_0.3.0                  viridis_0.6.2               grid_4.2.2                  blob_1.2.4                 
[111] digest_0.6.31               gridGraphics_0.5-1          munsell_0.5.0               viridisLite_0.4.1           ggplotify_0.1.0     

When I use
BiocManager::install("depmap")
**And The same error occurred:**
Warning: package 'dplyr' was built under R version 4.2.3
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
snapshotDate(): 2023-04-11
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: FUN(X[[i]], ...)
  error: 'crispr_22Q1' not found in ExperimentHub
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by lgatto** [comment] 2023-04-13 06:09
This is weird:

``` 
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
```

are you on-line when running the code? Make sure you are, then do the following:

```
BiocManager::install("ExperimentHub")
library(ExperimentHub)
eh <- ExperimentHub()
query(eh, "crispr_2")
```
What do you get?

**Comment by Travis13197** [comment] 2023-04-13 07:41
> library(ExperimentHub)
> eh <- ExperimentHub()
  |===================================================================================================================================================| 100%

snapshotDate(): 2022-10-31
> query(eh, "crispr_2")
ExperimentHub with 10 records
# snapshotDate(): 2022-10-31
# $dataprovider: Broad Institute
# $species: Homo sapiens
# $rdataclass: tibble
# additional mcols(): taxonomyid, genome, description, coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags, rdatapath,
#   sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH3290"]]' 

           title      
  EH3290 | crispr_20Q1
  EH3454 | crispr_20Q2
  EH3797 | crispr_20Q3
  EH3960 | crispr_20Q4
  EH5358 | crispr_21Q1
  EH6118 | crispr_21Q2
  EH6753 | crispr_21Q3
  EH7290 | crispr_21Q4
  EH7523 | crispr_22Q1
  EH7554 | crispr_22Q2

it seemed that crispr_22Q1 was downloaded. 

**but after running above codes, i re-ran **
`BiocManager::install("depmap")`
same errors occurred:

Warning: package 'dplyr' was built under R version 4.2.3
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
snapshotDate(): 2023-04-12
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: FUN(X[[i]], ...)
  error: 'crispr_22Q1' not found in ExperimentHub
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/刘传扬/AppData/Local/R/win-library/4.2/depmap'

it seems like a network problem(can not connect to ExperimentHub server), however it is quite strange that when i ran `eh <- ExperimentHub()`: it could download related data.

**Comment by lgatto** [comment] 2023-04-13 10:34
You are not showing everything - there's more code after typing `BiocManager::install("depmap")`:

```
> BiocManager::install("depmap")
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.2 Patched (2022-11-02
  r83238)
Installing package(s) 'depmap'
trying URL 'https://bioconductor.org/packages/3.16/data/experiment/src/contrib/depmap_1.12.0.tar.gz'
Content type 'application/x-gzip' length 1382308 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

* installing *source* package ‘depmap’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
snapshotDate(): 2022-10-31
** testing if installed package can be loaded from final location
snapshotDate(): 2022-10-31
** testing if installed package keeps a record of temporary installation path
* DONE (depmap)
```
Is you issue happening after the `** testing if installed package can be loaded from temporary location`? 

Are you sure you don't have intermittent network issues?

**Comment by Travis13197** [comment] 2023-04-13 12:34
```
> BiocManager::install("depmap")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://mirror.lzu.edu.cn/CRAN/
Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.2 (2022-10-31 ucrt)
Installing package(s) 'depmap'
安装源码包‘depmap’

trying URL 'https://bioconductor.org/packages/3.16/data/experiment/src/contrib/depmap_1.12.0.tar.gz'
Content type 'application/x-gzip' length 1382308 bytes (1.3 MB)
downloaded 1.3 MB

* installing *source* package 'depmap' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Warning message:
package 'dplyr' was built under R version 4.2.3 
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning: package 'dplyr' was built under R version 4.2.3
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
snapshotDate(): 2023-04-12
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: FUN(X[[i]], ...)
  error: 'crispr_22Q1' not found in ExperimentHub
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/kkk/AppData/Local/R/win-library/4.2/depmap'

下载的程序包在
	‘C:\Users\kkk\AppData\Local\Temp\Rtmp8Sm0vd\downloaded_packages’里
Old packages: 'DelayedArray', 'git2r', 'leidenbase', 'pec', 'RSQLite', 'lattice', 'Matrix'
```

**Comment by lgatto** [comment] 2023-04-13 12:47
I can reproduce your error if I close the wifi right after the package has downloaded, i.e at `installing *source* package 'depmap' ...`. Do you have any reasons to believe that there are some network restrictions on your computer? 

I would suggest you ask you question on the Bioconductor form, so gather wider input on this issue.

**Comment by 0106WeiWeiDeng** [comment] 2023-10-26 03:06
Try :
1. download package from bioconductor website: [depmap_1.15.0.tar.gz](https://bioconductor.org/packages/release/data/experiment/src/contrib/depmap_1.15.0.tar.gz)
2. in terminal: R CMD INSTALL  depmap_1.15.0.tar.gz

**Comment by soleded** [comment] 2023-10-27 14:25
I have the similar question, and don't know how to solve this problem
> BiocManager::install("uclouvain-cbio/depmap")
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://mirror-hk.koddos.net/CRAN/
Bioconductor version 3.17 (BiocManager 1.30.22), R 4.3.1 (2023-06-16 ucrt)
Installing github package(s) 'uclouvain-cbio/depmap'
Downloading GitHub repo uclouvain-cbio/depmap@HEAD
Running `R CMD build`...
* checking for file 'C:\Users\SOLEDED\AppData\Local\Temp\RtmpYTP78I\remotes49a426b768b8\UCLouvain-CBIO-depmap-f716330/DESCRIPTION' ... OK
* preparing 'depmap':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'depmap_1.11.2.tar.gz'
* installing *source* package 'depmap' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: (function (cond) 
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/SOLEDED/AppData/Local/R/win-library/4.3/depmap'
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.3.1/library
  packages:
    foreign, KernSmooth, lattice, Matrix, mgcv, nlme, rpart, spatial, survival
Warning message:
In i.p(...) :
  安装程序包‘C:/Users/SOLEDED/AppData/Local/Temp/RtmpYTP78I/file49a46d152fd1/depmap_1.11.2.tar.gz’时退出狀態的值不是0

**Comment by lgatto** [comment] 2023-10-27 18:01
This is a different issue - see [here](https://community-bioc.slack.com/archives/C02A1B8HUHZ/p1698321709283819?thread_ts=1697654650.083739&cid=C02A1B8HUHZ) (if you are on the Bioconductor slack).

In a nutshell:
- wait 24 hours, update `BiocFileCache`, et try again
- if you can wait, `BiocManager::install("Bioconductor/BiocFileCache")`

**Comment by YanlanSun** [comment] 2023-12-21 05:46
I also face the similar problem, can you give me sone suggestions? Thank you very much!
BiocManager::install("depmap")
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://mirrors.tuna.tsinghua.edu.cn/CRAN/
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.2 (2023-10-31 ucrt)
Installing package(s) 'depmap'
安装源码包‘depmap’

试开URL’https://bioconductor.org/packages/3.18/data/experiment/src/contrib/depmap_1.16.0.tar.gz'
Content type 'application/x-gzip' length 1409559 bytes (1.3 MB)
downloaded 1.3 MB

* installing *source* package 'depmap' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: h(simpleError(msg, call))
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/R/R-4.3.2/library/depmap'

下载的程序包在
	‘C:\Users\18817\AppData\Local\Temp\RtmpSyRljJ\downloaded_packages’里
Old packages: 'mgcv'
Update all/some/none? [a/s/n]: 
a

  有二进制版本的，但源代码版本是后来的:
     binary source needs_compilation
mgcv  1.9-0  1.9-1              TRUE

  Binaries will be installed
试开URL’https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/4.3/mgcv_1.9-0.zip'
Content type 'application/zip' length 3389936 bytes (3.2 MB)
downloaded 3.2 MB

程序包‘mgcv’打开成功，MD5和检查也通过

下载的二进制程序包在
	C:\Users\18817\AppData\Local\Temp\RtmpSyRljJ\downloaded_packages里
Warning message:
In install.packages(...) : 安装程序包‘depmap’时退出狀態的值不是0

**Comment by YanlanSun** [comment] 2023-12-21 06:55
I want to install MAGeCKFlute, but the dependency "depmap" is not available, can I slove this problem through 

**wait 24 hours, update BiocFileCache, et try again
if you can wait, BiocManager::install("Bioconductor/BiocFileCache")
and try again**

I am confused why I have to wait 24h and waiting 24h before or after **BiocManager::install("Bioconductor/BiocFileCache")**
Thank you very much!

> devtools::install_github("liulab-dfci/MAGeCKFlute")
Downloading GitHub repo liulab-dfci/MAGeCKFlute@HEAD
Installing 1 packages: depmap
安装源码包‘depmap’

试开URL’https://bioconductor.org/packages/3.18/data/experiment/src/contrib/depmap_1.16.0.tar.gz'
Content type 'application/x-gzip' length 1409559 bytes (1.3 MB)
downloaded 1.3 MB

* installing *source* package 'depmap' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: h(simpleError(msg, call))
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/R/R-4.3.2/library/depmap'

下载的程序包在
	‘C:\Users\18817\AppData\Local\Temp\RtmpkBpBQZ\downloaded_packages’里
── R CMD build ──────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\18817\AppData\Local\Temp\RtmpkBpBQZ\remotes5b823a16ed4\liulab-dfci-MAGeCKFlute-20a356c/DESCRIPTION'
─  preparing 'MAGeCKFlute': (965ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'MAGeCKFlute_1.99.0.tar.gz'
   
ERROR: dependency 'depmap' is not available for package 'MAGeCKFlute'
* removing 'D:/R/R-4.3.2/library/MAGeCKFlute'
Warning messages:
1: In i.p(...) : 安装程序包‘depmap’时退出狀態的值不是0
2: In i.p(...) :
  安装程序包‘C:/Users/18817/AppData/Local/Temp/RtmpkBpBQZ/file5b855db384f/MAGeCKFlute_1.99.0.tar.gz’时退出狀態的值不是0

**Comment by lgatto** [comment] 2023-12-21 07:56
Try to load ExperimentHub, to create the cache and/or see the instructions in the error message.

**Comment by YanlanSun** [comment] 2023-12-21 08:22
when I try to load ExperimentHub, it still indicates connecting unsuccessfully, what I can do?

![image](https://github.com/UCLouvain-CBIO/depmap/assets/149571835/a616a919-6675-4dfb-a6fb-be55ce742258)

**Comment by lgatto** [comment] 2023-12-21 09:39
Have you tried following the instructions? 

Otherwise, please ask on https://support.bioconductor.org/

**Closed** 2024-01-31 20:28 UTC
